import json
import os

modulos_por_asignatura = {
    "Lenguaje": ["Lenguaje y Comunicación", "Taller de Comprensión Lectora", "Reforzamiento de Lenguaje"],
    "Matemática": ["Matemática", "Reforzamiento de Matemática"],
    "Ciencias e Historia": ["Ciencias Naturales", "Historia, Geografía y Ciencias Sociales"],
    "Inglés": ["English", "English With Fun"],
    "Artes y Creatividad": ["Educación Artística", "Teoría Musical", "Interpretación Musical", "Robótica"],
    "Desarrollo Integral": ["Educación Socioemocional", "Taller de Funciones Ejecutivas", "Taller de Movimiento y Coordinación"]
}

preguntas_base = [
    # --- Lenguaje y Comunicación (min 10) ---
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Lectura", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Cuál de estas palabras es un sustantivo propio?", "opciones": ["perro", "Marta", "ciudad", "lápiz"], "respuesta_correcta": "Marta", "retroalimentacion": "Los sustantivos propios nombran a personas, lugares o mascotas específicas y siempre se escriben con mayúscula inicial."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Escritura", "oa": "OA 12", "dificultad": "Media", "pregunta": "¿Qué signo de puntuación se usa para hacer una pregunta?", "opciones": ["Punto (.)", "Coma (,)", "Signos de interrogación (¿?)", "Signos de exclamación (¡!)"], "respuesta_correcta": "Signos de interrogación (¿?)", "retroalimentacion": "Los signos de interrogación se utilizan al principio y al final para indicar una pregunta."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Lectura", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Qué palabra es un adjetivo?", "opciones": ["correr", "hermoso", "mesa", "ayer"], "respuesta_correcta": "hermoso", "retroalimentacion": "Los adjetivos describen características de los sustantivos, como 'hermoso'."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Escritura", "oa": "OA 12", "dificultad": "Media", "pregunta": "¿Dónde se usa el punto y aparte?", "opciones": ["Para separar palabras", "Al final de una oración", "Al final de un párrafo", "Para hacer una pregunta"], "respuesta_correcta": "Al final de un párrafo", "retroalimentacion": "El punto y aparte marca el final de un párrafo y separa ideas distintas."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Comunicación Oral", "oa": "OA 27", "dificultad": "Fácil", "pregunta": "Cuando alguien expone sobre un tema, tú debes...", "opciones": ["Gritar", "Escuchar con atención", "Dormir", "Jugar con el lápiz"], "respuesta_correcta": "Escuchar con atención", "retroalimentacion": "Escuchar con atención demuestra respeto hacia la persona que está hablando."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Lectura", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Cuál de estas palabras es un verbo?", "opciones": ["saltar", "gato", "rojo", "feliz"], "respuesta_correcta": "saltar", "retroalimentacion": "Los verbos indican acciones que realizan los sujetos."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Escritura", "oa": "OA 13", "dificultad": "Media", "pregunta": "¿Cuál palabra está escrita en plural?", "opciones": ["árbol", "mesas", "sol", "perro"], "respuesta_correcta": "mesas", "retroalimentacion": "El plural indica que hay más de un objeto, usualmente terminando en 's'."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Lectura", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuál de estos es un sinónimo de 'feliz'?", "opciones": ["triste", "enojado", "contento", "rápido"], "respuesta_correcta": "contento", "retroalimentacion": "Los sinónimos son palabras diferentes que significan lo mismo."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Lectura", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué es el antónimo de 'grande'?", "opciones": ["enorme", "pequeño", "lindo", "fuerte"], "respuesta_correcta": "pequeño", "retroalimentacion": "Los antónimos son palabras que significan lo contrario."},
    {"modulo_eduhome": "Lenguaje y Comunicación", "eje": "Escritura", "oa": "OA 14", "dificultad": "Difícil", "pregunta": "¿Qué tipo de texto narra hechos reales de la actualidad?", "opciones": ["Un cuento", "Una leyenda", "Una noticia", "Un poema"], "respuesta_correcta": "Una noticia", "retroalimentacion": "Las noticias informan de manera objetiva sobre cosas que suceden en la realidad."},

    # --- Taller de Comprensión Lectora (min 10) ---
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Media", "pregunta": "Si un cuento dice 'Había una vez en un bosque encantado...', ¿de qué parte del cuento estamos hablando?", "opciones": ["El final", "El desarrollo", "El inicio", "El título"], "respuesta_correcta": "El inicio", "retroalimentacion": "El inicio presenta a los personajes y el lugar donde ocurre la historia."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "En el cuento de Caperucita Roja, ¿quién es el personaje principal?", "opciones": ["El lobo", "La abuelita", "Caperucita Roja", "El cazador"], "respuesta_correcta": "Caperucita Roja", "retroalimentacion": "El personaje principal es el más importante de la historia."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Qué es la moraleja de una fábula?", "opciones": ["El título", "El dibujo", "Una enseñanza o lección", "El autor"], "respuesta_correcta": "Una enseñanza o lección", "retroalimentacion": "Las fábulas siempre dejan una enseñanza llamada moraleja al final."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "Si el texto dice 'Las nubes estaban oscuras y se escuchaban truenos', ¿qué podemos inferir?", "opciones": ["Que va a salir el sol", "Que es de noche", "Que va a llover fuerte", "Que es primavera"], "respuesta_correcta": "Que va a llover fuerte", "retroalimentacion": "Inferir es usar pistas del texto para descubrir algo que no está escrito directamente."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Qué tipo de texto es una receta de cocina?", "opciones": ["Texto poético", "Texto instructivo", "Cuento", "Noticia"], "respuesta_correcta": "Texto instructivo", "retroalimentacion": "Las recetas dan instrucciones paso a paso para preparar algo."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué significa cuando un personaje está 'temblando de miedo'?", "opciones": ["Que tiene calor", "Que está muy asustado", "Que tiene hambre", "Que quiere jugar"], "respuesta_correcta": "Que está muy asustado", "retroalimentacion": "El cuerpo reacciona temblando cuando sentimos un susto o miedo muy grande."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "En un texto, ¿qué información nos da el título?", "opciones": ["El precio del libro", "El nombre de la historia", "La edad del autor", "El color de las páginas"], "respuesta_correcta": "El nombre de la historia", "retroalimentacion": "El título nos anticipa de qué se tratará la lectura."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "Si lees: 'Juan corría hacia la meta sudando y sin aire', ¿qué está haciendo Juan?", "opciones": ["Durmiendo", "Comiendo", "Participando en una carrera", "Viendo la televisión"], "respuesta_correcta": "Participando en una carrera", "retroalimentacion": "Podemos deducir que está en una carrera por las palabras 'meta', 'corría' y 'sudando'."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 5", "dificultad": "Media", "pregunta": "¿Qué expresa principalmente un poema?", "opciones": ["Noticias del día", "Sentimientos y emociones", "Pasos para armar un juguete", "Datos sobre animales"], "respuesta_correcta": "Sentimientos y emociones", "retroalimentacion": "Los poemas están escritos en verso y buscan expresar la belleza y los sentimientos del autor."},
    {"modulo_eduhome": "Taller de Comprensión Lectora", "eje": "Lectura", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Cuál es el propósito de una leyenda?", "opciones": ["Vender un producto", "Dar instrucciones", "Explicar el origen de algo con fantasía y realidad", "Enseñar a sumar"], "respuesta_correcta": "Explicar el origen de algo con fantasía y realidad", "retroalimentacion": "Las leyendas son relatos tradicionales que mezclan hechos reales con magia para explicar fenómenos."},

    # --- Reforzamiento de Lenguaje (min 10) ---
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuántas sílabas tiene la palabra 'Elefante'?", "opciones": ["2", "3", "4", "5"], "respuesta_correcta": "4", "retroalimentacion": "La palabra se divide así: E - le - fan - te."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuál es la letra inicial de 'Sol'?", "opciones": ["A", "S", "M", "L"], "respuesta_correcta": "S", "retroalimentacion": "La palabra Sol comienza con la letra S."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Escritura", "oa": "OA 12", "dificultad": "Media", "pregunta": "Identifica la palabra escrita correctamente:", "opciones": ["Hárbol", "Árbol", "Harbol", "Arvol"], "respuesta_correcta": "Árbol", "retroalimentacion": "La palabra correcta es 'Árbol' y lleva tilde por ser grave terminada en 'l'."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué rima con 'gato'?", "opciones": ["Perro", "Ratón", "Zapato", "Casa"], "respuesta_correcta": "Zapato", "retroalimentacion": "Gato y zapato terminan con el mismo sonido '-ato'."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Escritura", "oa": "OA 12", "dificultad": "Fácil", "pregunta": "Las oraciones siempre deben comenzar con...", "opciones": ["Un dibujo", "Punto final", "Mayúscula", "Una coma"], "respuesta_correcta": "Mayúscula", "retroalimentacion": "La regla general de escritura es empezar toda oración con letra mayúscula."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Qué letra falta en la palabra _esa (mueble para comer)?", "opciones": ["p", "m", "s", "t"], "respuesta_correcta": "m", "retroalimentacion": "La palabra es 'mesa'."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 3", "dificultad": "Media", "pregunta": "Si unimos las sílabas ca-mi-sa, formamos la palabra:", "opciones": ["cama", "camisa", "casa", "misa"], "respuesta_correcta": "camisa", "retroalimentacion": "Al juntar ca + mi + sa, leemos 'camisa'."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Escritura", "oa": "OA 12", "dificultad": "Fácil", "pregunta": "Los nombres de países, como Chile, se escriben con:", "opciones": ["minúscula", "color rojo", "mayúscula", "letras grandes al final"], "respuesta_correcta": "mayúscula", "retroalimentacion": "Chile es un sustantivo propio y los sustantivos propios empiezan con mayúscula."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Lectura", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Cuál de estas palabras es aguda?", "opciones": ["reloj", "mesa", "lápiz", "cámara"], "respuesta_correcta": "reloj", "retroalimentacion": "Las palabras agudas cargan la voz en la última sílaba, como re-LOJ."},
    {"modulo_eduhome": "Reforzamiento de Lenguaje", "eje": "Escritura", "oa": "OA 12", "dificultad": "Difícil", "pregunta": "¿En qué oración se usa bien la coma?", "opciones": ["Compré, manzanas, peras, y plátanos", "Compré manzanas, peras y plátanos.", "Compré manzanas peras y, plátanos.", "Compré manzanas, peras, y, plátanos."], "respuesta_correcta": "Compré manzanas, peras y plátanos.", "retroalimentacion": "La coma se usa para separar elementos de una enumeración, pero no antes de la 'y' final."},

    # --- Matemática (min 10) ---
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "¿Cuánto es 8 + 5?", "opciones": ["12", "13", "14", "15"], "respuesta_correcta": "13", "retroalimentacion": "8 más 2 es 10, y te faltan 3 más, así que 10 + 3 = 13."},
    {"modulo_eduhome": "Matemática", "eje": "Geometría", "oa": "OA 14", "dificultad": "Media", "pregunta": "¿Cuántos lados tiene un triángulo?", "opciones": ["2", "3", "4", "5"], "respuesta_correcta": "3", "retroalimentacion": "La palabra 'tri' significa tres, por lo que un triángulo es una figura de 3 lados."},
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Qué número viene después del 199?", "opciones": ["100", "200", "198", "201"], "respuesta_correcta": "200", "retroalimentacion": "Después de contar hasta el 99, pasamos a la siguiente centena, que es el 200."},
    {"modulo_eduhome": "Matemática", "eje": "Medición", "oa": "OA 19", "dificultad": "Fácil", "pregunta": "Si el reloj pequeño marca las 3 y el reloj grande marca las 12, ¿qué hora es?", "opciones": ["Las 12", "Las 3 en punto", "Las 3 y media", "Las 4"], "respuesta_correcta": "Las 3 en punto", "retroalimentacion": "La manecilla pequeña indica la hora y la grande en el 12 indica que son 'en punto'."},
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 9", "dificultad": "Difícil", "pregunta": "¿Cuál es la mitad de 10?", "opciones": ["2", "4", "5", "8"], "respuesta_correcta": "5", "retroalimentacion": "Si tienes 10 dulces y los divides en 2 partes iguales, cada parte tiene 5 dulces."},
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuánto es 15 menos 5?", "opciones": ["5", "10", "20", "0"], "respuesta_correcta": "10", "retroalimentacion": "Si a 15 le quitas 5, te quedas con 10."},
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 8", "dificultad": "Media", "pregunta": "¿Cuánto es 3 veces 4? (3 x 4)", "opciones": ["7", "10", "12", "16"], "respuesta_correcta": "12", "retroalimentacion": "Es lo mismo que sumar 4 + 4 + 4, que es igual a 12."},
    {"modulo_eduhome": "Matemática", "eje": "Geometría", "oa": "OA 15", "dificultad": "Fácil", "pregunta": "¿Qué figura tiene 4 lados iguales?", "opciones": ["Círculo", "Triángulo", "Rectángulo", "Cuadrado"], "respuesta_correcta": "Cuadrado", "retroalimentacion": "El cuadrado es una figura geométrica de cuatro lados exactamente iguales."},
    {"modulo_eduhome": "Matemática", "eje": "Medición", "oa": "OA 21", "dificultad": "Media", "pregunta": "¿Con qué instrumento mides tu peso?", "opciones": ["Una regla", "Un reloj", "Una balanza", "Un termómetro"], "respuesta_correcta": "Una balanza", "retroalimentacion": "La balanza o pesa nos permite saber cuántos kilos pesa una persona o un objeto."},
    {"modulo_eduhome": "Matemática", "eje": "Números y Operaciones", "oa": "OA 5", "dificultad": "Difícil", "pregunta": "Tengo 5 monedas de $10 y 2 monedas de $100. ¿Cuánto dinero tengo?", "opciones": ["$150", "$250", "$105", "$52"], "respuesta_correcta": "$250", "retroalimentacion": "2 de $100 son $200. Y 5 de $10 son $50. Al sumar $200 + $50 da $250."},

    # --- Reforzamiento de Matemática (min 10) ---
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 8", "dificultad": "Difícil", "pregunta": "Si tienes 3 cajas y cada caja tiene 4 manzanas, ¿cuántas manzanas tienes en total?", "opciones": ["7", "10", "12", "14"], "respuesta_correcta": "12", "retroalimentacion": "Puedes sumar 4 + 4 + 4 o multiplicar 3 x 4, lo que da 12 manzanas."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuánto es 10 - 4?", "opciones": ["4", "5", "6", "7"], "respuesta_correcta": "6", "retroalimentacion": "Si a 10 le quitas 4, te quedan 6."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Cuál es el resultado de 15 + 15?", "opciones": ["20", "25", "30", "35"], "respuesta_correcta": "30", "retroalimentacion": "10 + 10 son 20, y 5 + 5 son 10. Sumando ambos da 30."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 8", "dificultad": "Media", "pregunta": "Calcula: 2 x 5", "opciones": ["5", "7", "10", "12"], "respuesta_correcta": "10", "retroalimentacion": "Sumar 5 dos veces da como resultado 10."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Patrones y Álgebra", "oa": "OA 12", "dificultad": "Difícil", "pregunta": "Completa la secuencia: 2, 4, 6, 8, ___", "opciones": ["9", "10", "12", "14"], "respuesta_correcta": "10", "retroalimentacion": "La secuencia avanza de 2 en 2, sumando 2 al último número: 8 + 2 = 10."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Cuánto es 20 + 5?", "opciones": ["15", "25", "30", "205"], "respuesta_correcta": "25", "retroalimentacion": "Al sumar 20 más 5 obtienes 25."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 3", "dificultad": "Media", "pregunta": "Si tenía 30 dulces y me comí 10, ¿cuántos me quedan?", "opciones": ["10", "20", "40", "15"], "respuesta_correcta": "20", "retroalimentacion": "30 menos 10 es igual a 20."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Números y Operaciones", "oa": "OA 8", "dificultad": "Media", "pregunta": "¿Cuánto es 5 veces 2? (5 x 2)", "opciones": ["7", "10", "20", "15"], "respuesta_correcta": "10", "retroalimentacion": "Contar de a 2, cinco veces: 2, 4, 6, 8, 10."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Geometría", "oa": "OA 15", "dificultad": "Fácil", "pregunta": "¿Qué figura no tiene esquinas ni lados rectos?", "opciones": ["Cuadrado", "Triángulo", "Círculo", "Rectángulo"], "respuesta_correcta": "Círculo", "retroalimentacion": "El círculo es una figura redonda y curva, sin esquinas ni lados rectos."},
    {"modulo_eduhome": "Reforzamiento de Matemática", "eje": "Patrones y Álgebra", "oa": "OA 12", "dificultad": "Difícil", "pregunta": "Completa: 10, 20, 30, ___", "opciones": ["35", "40", "50", "100"], "respuesta_correcta": "40", "retroalimentacion": "La secuencia avanza sumando de a 10 cada vez."},

    # --- Ciencias Naturales (min 10) ---
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Vida", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Qué necesitan las plantas para realizar la fotosíntesis?", "opciones": ["Solo agua", "Agua, luz solar y dióxido de carbono", "Azúcar y sal", "Solo tierra"], "respuesta_correcta": "Agua, luz solar y dióxido de carbono", "retroalimentacion": "Las plantas fabrican su propio alimento usando la luz, agua y aire."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Tierra y el Universo", "oa": "OA 11", "dificultad": "Fácil", "pregunta": "¿Cuál es el planeta en el que vivimos?", "opciones": ["Marte", "Venus", "Tierra", "Júpiter"], "respuesta_correcta": "Tierra", "retroalimentacion": "Vivimos en la Tierra, el tercer planeta desde el Sol."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias Físicas", "oa": "OA 8", "dificultad": "Media", "pregunta": "¿Cuál de estos materiales es transparente?", "opciones": ["Madera", "Metal", "Vidrio", "Piedra"], "respuesta_correcta": "Vidrio", "retroalimentacion": "El vidrio permite que la luz pase a través de él."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Vida", "oa": "OA 6", "dificultad": "Fácil", "pregunta": "¿Qué animal es un mamífero?", "opciones": ["Pez", "Gallina", "Perro", "Mosca"], "respuesta_correcta": "Perro", "retroalimentacion": "Los mamíferos, como los perros, nacen del vientre de la madre y toman leche."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias Físicas", "oa": "OA 9", "dificultad": "Difícil", "pregunta": "¿Qué pasa si calentamos mucho el hielo?", "opciones": ["Se vuelve más duro", "Se derrite y se vuelve líquido", "Desaparece", "Se convierte en piedra"], "respuesta_correcta": "Se derrite y se vuelve líquido", "retroalimentacion": "El calor hace que el agua en estado sólido (hielo) pase a estado líquido."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Vida", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué parte de la planta absorbe el agua?", "opciones": ["Las hojas", "Las flores", "La raíz", "El tallo"], "respuesta_correcta": "La raíz", "retroalimentacion": "La raíz absorbe el agua y los minerales del suelo para alimentar a la planta."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Tierra y el Universo", "oa": "OA 12", "dificultad": "Fácil", "pregunta": "¿Qué astro nos da luz y calor durante el día?", "opciones": ["La Luna", "Las estrellas", "El Sol", "Marte"], "respuesta_correcta": "El Sol", "retroalimentacion": "El Sol es la estrella más cercana a nosotros y nos ilumina de día."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias Físicas", "oa": "OA 8", "dificultad": "Fácil", "pregunta": "¿Qué material es más suave?", "opciones": ["Algodón", "Piedra", "Madera", "Hierro"], "respuesta_correcta": "Algodón", "retroalimentacion": "El algodón tiene una textura muy suave, a diferencia de los otros materiales duros."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Vida", "oa": "OA 6", "dificultad": "Media", "pregunta": "¿Qué animales nacen por huevos?", "opciones": ["Ovíparos", "Mamíferos", "Herbívoros", "Carnívoros"], "respuesta_correcta": "Ovíparos", "retroalimentacion": "Los animales ovíparos, como las aves y los reptiles, nacen a partir de huevos."},
    {"modulo_eduhome": "Ciencias Naturales", "eje": "Ciencias de la Vida", "oa": "OA 7", "dificultad": "Difícil", "pregunta": "¿Cómo respiran los peces bajo el agua?", "opciones": ["Por pulmones", "Por branquias", "Por la piel", "No respiran"], "respuesta_correcta": "Por branquias", "retroalimentacion": "Los peces utilizan las branquias para extraer el oxígeno disuelto en el agua."},

    # --- Historia, Geografía y Ciencias Sociales (min 10) ---
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Geografía", "oa": "OA 7", "dificultad": "Fácil", "pregunta": "¿En qué continente se encuentra Chile?", "opciones": ["Europa", "Asia", "África", "América"], "respuesta_correcta": "América", "retroalimentacion": "Chile está ubicado en América del Sur."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Geografía", "oa": "OA 8", "dificultad": "Media", "pregunta": "¿Cuál es la capital de Chile?", "opciones": ["Valparaíso", "Concepción", "Santiago", "Antofagasta"], "respuesta_correcta": "Santiago", "retroalimentacion": "Santiago es la ciudad capital de Chile."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Historia", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Quiénes vivían en Chile antes de la llegada de los españoles?", "opciones": ["Solo dinosaurios", "Los pueblos originarios", "Nadie", "Los ingleses"], "respuesta_correcta": "Los pueblos originarios", "retroalimentacion": "Los pueblos originarios, como los Mapuches y Aymaras, habitaban este territorio."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Geografía", "oa": "OA 7", "dificultad": "Media", "pregunta": "¿Qué gran océano baña las costas de Chile?", "opciones": ["Océano Atlántico", "Océano Índico", "Océano Pacífico", "Océano Ártico"], "respuesta_correcta": "Océano Pacífico", "retroalimentacion": "Todo el largo de Chile limita al oeste con el Océano Pacífico."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Formación Ciudadana", "oa": "OA 11", "dificultad": "Difícil", "pregunta": "¿Por qué son importantes las normas de convivencia en la sala de clases?", "opciones": ["Para tener más recreos", "Para que todos se respeten y aprendan mejor", "Para pintar las paredes", "Para no hacer tareas"], "respuesta_correcta": "Para que todos se respeten y aprendan mejor", "retroalimentacion": "Las normas nos ayudan a mantener el respeto y el orden."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Geografía", "oa": "OA 9", "dificultad": "Fácil", "pregunta": "¿Cómo es la forma de Chile en el mapa?", "opciones": ["Cuadrado", "Redondo", "Largo y angosto", "Corto y ancho"], "respuesta_correcta": "Largo y angosto", "retroalimentacion": "Chile se caracteriza por ser una franja de tierra larga y angosta."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Historia", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué pueblo originario habita principalmente en la zona sur de Chile?", "opciones": ["Mapuche", "Aymara", "Rapa Nui", "Diaguita"], "respuesta_correcta": "Mapuche", "retroalimentacion": "El pueblo Mapuche es originario y muy importante en la zona sur de nuestro país."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Formación Ciudadana", "oa": "OA 12", "dificultad": "Fácil", "pregunta": "¿Qué debemos hacer si vemos a un abuelito tratando de cruzar la calle?", "opciones": ["Correr a su lado riendo", "Ignorarlo", "Ayudarlo si es posible y respetarlo", "Cruzar antes que él"], "respuesta_correcta": "Ayudarlo si es posible y respetarlo", "retroalimentacion": "Es importante respetar y ayudar a las personas mayores."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Geografía", "oa": "OA 8", "dificultad": "Difícil", "pregunta": "¿Cuál es la cordillera que recorre todo Chile?", "opciones": ["Cordillera de los Alpes", "Cordillera del Himalaya", "Cordillera de los Andes", "Cordillera de la Costa"], "respuesta_correcta": "Cordillera de los Andes", "retroalimentacion": "La Cordillera de los Andes es la gran cadena montañosa que acompaña a Chile en el este."},
    {"modulo_eduhome": "Historia, Geografía y Ciencias Sociales", "eje": "Historia", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué comida es tradicional y típica de Chile?", "opciones": ["Sushi", "Empanada de pino", "Hamburguesa", "Tacos"], "respuesta_correcta": "Empanada de pino", "retroalimentacion": "Las empanadas de pino son una de las comidas típicas más conocidas de Chile."},

    # --- English (min 10) ---
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Cómo se dice 'Rojo' en inglés?", "opciones": ["Blue", "Green", "Red", "Yellow"], "respuesta_correcta": "Red", "retroalimentacion": "El color rojo se dice 'Red'."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Cómo se dice 'Hola' en inglés?", "opciones": ["Goodbye", "Hello", "Please", "Thank you"], "respuesta_correcta": "Hello", "retroalimentacion": "Hola en inglés es 'Hello'."},
    {"modulo_eduhome": "English", "eje": "Gramática", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué significa 'My name is...'?", "opciones": ["Me gusta...", "Yo tengo...", "Mi nombre es...", "Yo soy..."], "respuesta_correcta": "Mi nombre es...", "retroalimentacion": "Esta frase se usa para presentarse."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Cuál de estos es un número en inglés?", "opciones": ["Apple", "Book", "Seven", "Cat"], "respuesta_correcta": "Seven", "retroalimentacion": "Seven es el número 7."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Qué animal es 'Cat'?", "opciones": ["Perro", "Gato", "Pájaro", "Pez"], "respuesta_correcta": "Gato", "retroalimentacion": "Cat significa Gato."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué significa 'Dog'?", "opciones": ["Caballo", "Cerdo", "Perro", "Gato"], "respuesta_correcta": "Perro", "retroalimentacion": "Dog es perro en inglés."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Cómo decimos 'Adiós'?", "opciones": ["Hello", "Goodbye", "Please", "Sorry"], "respuesta_correcta": "Goodbye", "retroalimentacion": "Goodbye significa Adiós."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué color es 'Yellow'?", "opciones": ["Amarillo", "Verde", "Rojo", "Azul"], "respuesta_correcta": "Amarillo", "retroalimentacion": "Yellow es el color amarillo."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Cómo se dice 'Gracias'?", "opciones": ["Please", "Hello", "Thank you", "Sorry"], "respuesta_correcta": "Thank you", "retroalimentacion": "Thank you es la manera de dar las gracias en inglés."},
    {"modulo_eduhome": "English", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Cuál de estas palabras es un objeto del colegio?", "opciones": ["Pencil", "Dog", "Apple", "Car"], "respuesta_correcta": "Pencil", "retroalimentacion": "Pencil significa lápiz."},

    # --- English With Fun (min 10) ---
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué animal es un 'Dog'?", "opciones": ["Gato", "Perro", "Caballo", "Pájaro"], "respuesta_correcta": "Perro", "retroalimentacion": "'Dog' es la palabra en inglés para 'Perro'."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué color es 'Blue'?", "opciones": ["Rojo", "Azul", "Amarillo", "Verde"], "respuesta_correcta": "Azul", "retroalimentacion": "Blue es el color Azul."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué parte del cuerpo es 'Head'?", "opciones": ["Mano", "Pie", "Cabeza", "Ojo"], "respuesta_correcta": "Cabeza", "retroalimentacion": "Head significa Cabeza."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué comida es 'Apple'?", "opciones": ["Plátano", "Manzana", "Naranja", "Uva"], "respuesta_correcta": "Manzana", "retroalimentacion": "Apple es una Manzana."},
    {"modulo_eduhome": "English With Fun", "eje": "Expresión", "oa": "OA 4", "dificultad": "Difícil", "pregunta": "Si estás feliz, puedes decir: 'I am...'", "opciones": ["Sad", "Angry", "Happy", "Tired"], "respuesta_correcta": "Happy", "retroalimentacion": "Happy significa Feliz."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué animal es 'Bird'?", "opciones": ["Oso", "Pez", "Pájaro", "Serpiente"], "respuesta_correcta": "Pájaro", "retroalimentacion": "Bird es Pájaro en inglés."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Cómo se dice 'Sol' en inglés?", "opciones": ["Moon", "Star", "Cloud", "Sun"], "respuesta_correcta": "Sun", "retroalimentacion": "Sun significa Sol."},
    {"modulo_eduhome": "English With Fun", "eje": "Expresión", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "Para decir 'Por favor', dices:", "opciones": ["Sorry", "Thank you", "Please", "Hello"], "respuesta_correcta": "Please", "retroalimentacion": "Please es Por favor."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Qué color es 'Green'?", "opciones": ["Rojo", "Verde", "Negro", "Blanco"], "respuesta_correcta": "Verde", "retroalimentacion": "Green es el color Verde."},
    {"modulo_eduhome": "English With Fun", "eje": "Vocabulario", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "¿Qué significa 'Jump'?", "opciones": ["Correr", "Dormir", "Saltar", "Cantar"], "respuesta_correcta": "Saltar", "retroalimentacion": "Jump es la acción de Saltar."},

    # --- Educación Artística (min 10) ---
    {"modulo_eduhome": "Educación Artística", "eje": "Creación", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Cuáles son los colores primarios?", "opciones": ["Verde, Morado, Naranja", "Blanco, Negro, Gris", "Rojo, Azul, Amarillo", "Rosa, Celeste, Lila"], "respuesta_correcta": "Rojo, Azul, Amarillo", "retroalimentacion": "Los colores primarios son el rojo, el azul y el amarillo."},
    {"modulo_eduhome": "Educación Artística", "eje": "Creación", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué color obtienes si mezclas rojo y amarillo?", "opciones": ["Verde", "Naranja", "Morado", "Café"], "respuesta_correcta": "Naranja", "retroalimentacion": "La mezcla de rojo y amarillo crea el color naranja."},
    {"modulo_eduhome": "Educación Artística", "eje": "Materiales", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "¿Con qué material puedes modelar figuras 3D?", "opciones": ["Agua", "Lápiz", "Greda o Plasticina", "Papel"], "respuesta_correcta": "Greda o Plasticina", "retroalimentacion": "La plasticina nos permite crear objetos con volumen."},
    {"modulo_eduhome": "Educación Artística", "eje": "Apreciación", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Qué hace un escultor?", "opciones": ["Pinta cuadros", "Canta", "Crea estatuas y figuras", "Escribe poemas"], "respuesta_correcta": "Crea estatuas y figuras", "retroalimentacion": "Un escultor moldea o talla materiales para crear arte."},
    {"modulo_eduhome": "Educación Artística", "eje": "Creación", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Qué son las texturas visuales?", "opciones": ["Cosas que hacen ruido", "Dibujos que parecen tener volumen o rugosidad pero son planos", "La música de un video", "El olor de la pintura"], "respuesta_correcta": "Dibujos que parecen tener volumen o rugosidad pero son planos", "retroalimentacion": "Las texturas visuales engañan al ojo para que parezca que se pueden sentir."},
    {"modulo_eduhome": "Educación Artística", "eje": "Creación", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Qué color obtienes al mezclar Azul y Amarillo?", "opciones": ["Morado", "Verde", "Rojo", "Naranja"], "respuesta_correcta": "Verde", "retroalimentacion": "Al mezclar azul y amarillo, se crea el color verde."},
    {"modulo_eduhome": "Educación Artística", "eje": "Herramientas", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "¿Qué usamos comúnmente para pintar con témpera?", "opciones": ["Un tenedor", "Un pincel", "Una tijera", "Una regla"], "respuesta_correcta": "Un pincel", "retroalimentacion": "El pincel nos permite esparcir la pintura sobre el papel."},
    {"modulo_eduhome": "Educación Artística", "eje": "Apreciación", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Qué es un retrato?", "opciones": ["Un dibujo de un animal", "Un dibujo o pintura de la cara de una persona", "Una foto de un paisaje", "Una escultura de piedra"], "respuesta_correcta": "Un dibujo o pintura de la cara de una persona", "retroalimentacion": "El retrato es la representación gráfica de una persona."},
    {"modulo_eduhome": "Educación Artística", "eje": "Creación", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿A qué familia de colores pertenecen el Azul, el Morado y el Verde?", "opciones": ["Colores Cálidos", "Colores Fríos", "Colores Oscuros", "Colores Brillantes"], "respuesta_correcta": "Colores Fríos", "retroalimentacion": "Estos colores nos recuerdan al agua o al hielo, por eso son colores fríos."},
    {"modulo_eduhome": "Educación Artística", "eje": "Técnicas", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "¿En qué consiste la técnica del Collage?", "opciones": ["En pintar todo de negro", "En pegar distintos materiales y recortes en una hoja", "En cantar una canción", "En modelar con greda"], "respuesta_correcta": "En pegar distintos materiales y recortes en una hoja", "retroalimentacion": "El collage es una técnica de arte que une recortes de papel, telas, etc."},

    # --- Teoría Musical (min 10) ---
    {"modulo_eduhome": "Teoría Musical", "eje": "Apreciación", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué instrumento tiene teclas blancas y negras?", "opciones": ["Guitarra", "Batería", "Piano", "Flauta"], "respuesta_correcta": "Piano", "retroalimentacion": "El piano tiene un teclado con teclas blancas y negras."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Lenguaje Musical", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Cuántas líneas tiene un pentagrama?", "opciones": ["3", "4", "5", "6"], "respuesta_correcta": "5", "retroalimentacion": "Penta significa cinco, así que el pentagrama tiene 5 líneas."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Lenguaje Musical", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Cuál de estas es una nota musical?", "opciones": ["Sol", "Luna", "Estrella", "Nube"], "respuesta_correcta": "Sol", "retroalimentacion": "Las notas son Do, Re, Mi, Fa, Sol, La, Si."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Lenguaje Musical", "oa": "OA 2", "dificultad": "Difícil", "pregunta": "¿Qué símbolo se pone al principio del pentagrama?", "opciones": ["Una letra A", "La llave de Sol", "Un número 1", "Un punto"], "respuesta_correcta": "La llave de Sol", "retroalimentacion": "La llave de Sol indica cómo se leerán las notas."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Cualidades del Sonido", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Qué cualidad diferencia un sonido fuerte de uno suave?", "opciones": ["La altura", "La intensidad (volumen)", "La duración", "El timbre"], "respuesta_correcta": "La intensidad (volumen)", "retroalimentacion": "La intensidad nos dice si el sonido es muy fuerte o muy suavecito."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Instrumentos", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Qué instrumento se toca soplando?", "opciones": ["La flauta", "El piano", "La guitarra", "El tambor"], "respuesta_correcta": "La flauta", "retroalimentacion": "La flauta es un instrumento de viento y se toca soplando."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Lenguaje Musical", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Cuál es la primera nota musical de la escala básica?", "opciones": ["Sol", "Re", "Do", "Fa"], "respuesta_correcta": "Do", "retroalimentacion": "La escala musical comienza por lo general en 'Do'."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Instrumentos", "oa": "OA 4", "dificultad": "Media", "pregunta": "La guitarra pertenece a la familia de los instrumentos de...", "opciones": ["Percusión", "Viento", "Cuerda", "Eléctricos"], "respuesta_correcta": "Cuerda", "retroalimentacion": "La guitarra produce sonido al hacer vibrar sus cuerdas."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Cualidades del Sonido", "oa": "OA 3", "dificultad": "Media", "pregunta": "Si un sonido dura mucho tiempo o poquito tiempo, hablamos de su...", "opciones": ["Intensidad", "Altura", "Duración", "Timbre"], "respuesta_correcta": "Duración", "retroalimentacion": "La duración determina si el sonido es largo o corto."},
    {"modulo_eduhome": "Teoría Musical", "eje": "Lenguaje Musical", "oa": "OA 2", "dificultad": "Difícil", "pregunta": "¿Para qué sirven las figuras musicales (como la Negra, la Blanca)?", "opciones": ["Para indicar qué instrumento tocar", "Para marcar la duración del sonido en el tiempo", "Para adornar el papel", "Para saber si es fuerte o suave"], "respuesta_correcta": "Para marcar la duración del sonido en el tiempo", "retroalimentacion": "Las figuras como la Negra o Blanca nos dicen cuánto tiempo debe sonar una nota."},

    # --- Interpretación Musical (min 10) ---
    {"modulo_eduhome": "Interpretación Musical", "eje": "Apreciación", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Con qué parte del cuerpo aplaudimos al ritmo de la música?", "opciones": ["Los pies", "Las manos", "La cabeza", "Los hombros"], "respuesta_correcta": "Las manos", "retroalimentacion": "Usamos las manos para aplaudir."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Canto", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Qué usamos para cantar?", "opciones": ["Nuestra voz", "Los pies", "Los ojos", "Las orejas"], "respuesta_correcta": "Nuestra voz", "retroalimentacion": "La voz es nuestro instrumento musical natural."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Interpretación", "oa": "OA 5", "dificultad": "Media", "pregunta": "¿Qué es un coro?", "opciones": ["Un solo cantante", "Un grupo de personas cantando juntas", "Una guitarra sola", "Un baile"], "respuesta_correcta": "Un grupo de personas cantando juntas", "retroalimentacion": "Un coro está formado por muchas voces cantando a la vez."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Instrumentos", "oa": "OA 6", "dificultad": "Media", "pregunta": "¿Cómo se toca un tambor?", "opciones": ["Soplando", "Golpeándolo o percutiendo", "Frotando cuerdas", "Apretando teclas"], "respuesta_correcta": "Golpeándolo o percutiendo", "retroalimentacion": "El tambor es un instrumento de percusión."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Interpretación", "oa": "OA 5", "dificultad": "Difícil", "pregunta": "Cuando sigues el 'pulso' de una canción, estás...", "opciones": ["Durmiendo", "Marcando el latido constante de la música", "Cantando muy alto", "Tocando la flauta"], "respuesta_correcta": "Marcando el latido constante de la música", "retroalimentacion": "El pulso es como el latido del corazón de una canción."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Canto", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Qué es importante hacer antes de cantar mucho rato?", "opciones": ["Correr muy rápido", "Comer dulces", "Calentar la voz y respirar bien", "Gritar fuerte"], "respuesta_correcta": "Calentar la voz y respirar bien", "retroalimentacion": "Calentar las cuerdas vocales protege nuestra voz para no lastimarla."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Interpretación", "oa": "OA 5", "dificultad": "Media", "pregunta": "¿Qué es cantar 'a capella'?", "opciones": ["Cantar con una guitarra", "Cantar usando solo la voz, sin ningún instrumento musical", "Cantar con un piano", "Bailar sin cantar"], "respuesta_correcta": "Cantar usando solo la voz, sin ningún instrumento musical", "retroalimentacion": "Cantar a capella es usar solo las voces de las personas sin música de fondo."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Ritmo", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Qué instrumento nos ayuda a marcar bien el ritmo de una marcha?", "opciones": ["El violín", "La flauta dulce", "El bombo o la caja", "El arpa"], "respuesta_correcta": "El bombo o la caja", "retroalimentacion": "Los instrumentos de percusión son los mejores para marcar ritmos constantes."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Canto", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Cómo llamamos a la letra de una canción que se repite varias veces?", "opciones": ["El título", "El estribillo o coro", "El poema", "El cuento"], "respuesta_correcta": "El estribillo o coro", "retroalimentacion": "El estribillo es la parte de la canción que solemos aprendernos más fácil porque se repite."},
    {"modulo_eduhome": "Interpretación Musical", "eje": "Interpretación", "oa": "OA 6", "dificultad": "Difícil", "pregunta": "¿Quién es la persona encargada de guiar a una orquesta o a un coro con sus manos o una batuta?", "opciones": ["El cantante", "El director de orquesta", "El bailarín", "El pintor"], "respuesta_correcta": "El director de orquesta", "retroalimentacion": "El director marca el tiempo y las indicaciones para que todos toquen juntos y en armonía."},

    # --- Robótica (min 10) ---
    {"modulo_eduhome": "Robótica", "eje": "Tecnología", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Qué le dice al robot lo que tiene que hacer?", "opciones": ["Un motor", "Un código o programa", "Una rueda", "Un cable"], "respuesta_correcta": "Un código o programa", "retroalimentacion": "Los robots siguen instrucciones escritas en forma de código."},
    {"modulo_eduhome": "Robótica", "eje": "Componentes", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué parte de un robot le permite moverse?", "opciones": ["La batería", "Los sensores", "Los motores y ruedas", "Las luces"], "respuesta_correcta": "Los motores y ruedas", "retroalimentacion": "Los motores convierten la energía en movimiento para las ruedas o brazos."},
    {"modulo_eduhome": "Robótica", "eje": "Sensores", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "¿Cómo puede un robot 'ver' u 'oír'?", "opciones": ["Con ojos humanos", "Adivinando", "Usando sensores", "Con un reloj"], "respuesta_correcta": "Usando sensores", "retroalimentacion": "Los sensores le dan información del entorno (luz, distancia, sonido)."},
    {"modulo_eduhome": "Robótica", "eje": "Conceptos", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué necesita un robot para tener energía?", "opciones": ["Agua", "Baterías o electricidad", "Comida", "Sol solamente"], "respuesta_correcta": "Baterías o electricidad", "retroalimentacion": "Las máquinas electrónicas funcionan con energía eléctrica."},
    {"modulo_eduhome": "Robótica", "eje": "Programación", "oa": "OA 4", "dificultad": "Media", "pregunta": "En programación, ¿qué es un 'Bug'?", "opciones": ["Un insecto de verdad", "Un error en el código", "Una función nueva", "El nombre del robot"], "respuesta_correcta": "Un error en el código", "retroalimentacion": "Cuando el programa falla, se dice que tiene un 'bug' (error)."},
    {"modulo_eduhome": "Robótica", "eje": "Programación", "oa": "OA 4", "dificultad": "Fácil", "pregunta": "¿Quién crea los programas que usan los robots?", "opciones": ["Los animales", "Las plantas", "Los humanos (programadores)", "Los mismos robots"], "respuesta_correcta": "Los humanos (programadores)", "retroalimentacion": "Las personas escribimos los códigos para decirle a los robots qué hacer."},
    {"modulo_eduhome": "Robótica", "eje": "Tecnología", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Qué es un 'Algoritmo'?", "opciones": ["Una marca de robot", "Un tipo de motor", "Una serie de pasos ordenados para resolver un problema", "Un cable eléctrico"], "respuesta_correcta": "Una serie de pasos ordenados para resolver un problema", "retroalimentacion": "Un algoritmo es como una receta de pasos precisos para lograr algo en programación."},
    {"modulo_eduhome": "Robótica", "eje": "Sensores", "oa": "OA 3", "dificultad": "Media", "pregunta": "¿Para qué le sirve a un robot un sensor de distancia o de ultrasonido?", "opciones": ["Para hablar", "Para no chocar contra las paredes", "Para cambiar de color", "Para cargar su batería"], "respuesta_correcta": "Para no chocar contra las paredes", "retroalimentacion": "El sensor detecta objetos cercanos y así el robot puede frenar antes de chocar."},
    {"modulo_eduhome": "Robótica", "eje": "Componentes", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "Si un robot parece un humano (con brazos, piernas y cabeza), decimos que es un robot...", "opciones": ["Androide o humanoide", "Vehículo", "Avión", "Pelota"], "respuesta_correcta": "Androide o humanoide", "retroalimentacion": "Los robots humanoides tienen una forma parecida al cuerpo de las personas."},
    {"modulo_eduhome": "Robótica", "eje": "Tecnología", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Qué papel cumple el 'Cerebro' (microcontrolador) en un robot?", "opciones": ["Le da fuerza a las ruedas", "Es el que guarda la energía", "Procesa el código y da las órdenes a las partes", "Hace que el robot brille"], "respuesta_correcta": "Procesa el código y da las órdenes a las partes", "retroalimentacion": "El microcontrolador recibe la información de los sensores y manda instrucciones a los motores."},

    # --- Educación Socioemocional (min 10) ---
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Autoconocimiento", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué emoción sientes cuando te dan un regalo sorpresa que te gusta mucho?", "opciones": ["Tristeza", "Miedo", "Alegría", "Enojo"], "respuesta_correcta": "Alegría", "retroalimentacion": "La alegría es una emoción positiva que sentimos cuando ocurren cosas buenas."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Empatía", "oa": "OA 2", "dificultad": "Media", "pregunta": "Si un compañero se cae y llora, ¿qué es lo más empático que puedes hacer?", "opciones": ["Reírte", "Ignorarlo", "Preguntarle si está bien y ayudarlo", "Empujarlo"], "respuesta_correcta": "Preguntarle si está bien y ayudarlo", "retroalimentacion": "La empatía es entender lo que siente el otro y apoyarlo."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Regulación", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "Cuando estás muy enojado, ¿qué puedes hacer para calmarte?", "opciones": ["Gritar fuerte", "Respirar profundo y contar hasta 10", "Romper cosas", "Pegarle a la pared"], "respuesta_correcta": "Respirar profundo y contar hasta 10", "retroalimentacion": "Respirar hondo ayuda a que tu cuerpo y mente se relajen."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Resolución de conflictos", "oa": "OA 4", "dificultad": "Media", "pregunta": "Si tú y tu amigo quieren jugar juegos distintos, ¿cuál es la mejor solución?", "opciones": ["Pelear", "No jugar más", "Llegar a un acuerdo y jugar un rato cada uno", "Obligarlo a jugar el tuyo"], "respuesta_correcta": "Llegar a un acuerdo y jugar un rato cada uno", "retroalimentacion": "Llegar a un acuerdo es la mejor forma de resolver un conflicto pacíficamente."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Autoconcepto", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Qué significa tener buena autoestima?", "opciones": ["Creer que eres mejor que todos", "Quererte y aceptarte como eres", "Estar siempre triste", "No hablar con nadie"], "respuesta_correcta": "Quererte y aceptarte como eres", "retroalimentacion": "La autoestima es el aprecio y amor que te tienes a ti mismo."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Autoconocimiento", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "¿Qué emoción sueles sentir si te pierdes en un lugar desconocido?", "opciones": ["Miedo", "Alegría", "Hambre", "Risa"], "respuesta_correcta": "Miedo", "retroalimentacion": "El miedo es normal ante situaciones peligrosas o desconocidas."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Empatía", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Cómo crees que se siente un amigo si no lo invitan a jugar?", "opciones": ["Feliz", "Triste o excluido", "Emocionado", "Cansado"], "respuesta_correcta": "Triste o excluido", "retroalimentacion": "Ser dejado de lado suele causar tristeza."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Regulación", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "¿Qué puedes hacer si cometes un error?", "opciones": ["Enojarte mucho", "Llorar sin parar", "Aprender de él y volver a intentarlo", "Echarle la culpa a otro"], "respuesta_correcta": "Aprender de él y volver a intentarlo", "retroalimentacion": "Los errores son oportunidades maravillosas para aprender."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Resolución de conflictos", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Qué palabras son 'mágicas' para llevarse bien con los demás?", "opciones": ["Sal de aquí", "Por favor y Gracias", "No me importa", "Dame eso"], "respuesta_correcta": "Por favor y Gracias", "retroalimentacion": "Usar palabras amables mejora mucho la relación con las personas."},
    {"modulo_eduhome": "Educación Socioemocional", "eje": "Autoconcepto", "oa": "OA 1", "dificultad": "Difícil", "pregunta": "¿Qué debes recordar cuando algo te cuesta mucho trabajo?", "opciones": ["Que no sirves para nada", "Que debes rendirte", "Que con práctica y esfuerzo puedes lograrlo", "Que alguien más debe hacerlo por ti"], "respuesta_correcta": "Que con práctica y esfuerzo puedes lograrlo", "retroalimentacion": "La perseverancia es clave; no todos aprendemos al mismo ritmo."},

    # --- Taller de Funciones Ejecutivas (min 10) ---
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Organización", "oa": "OA 2", "dificultad": "Media", "pregunta": "Si tienes que hacer la tarea, jugar y cenar, ¿qué es mejor hacer primero?", "opciones": ["Jugar sin parar", "La tarea, luego jugar y después cenar", "No cenar y jugar", "Empezar la tarea y no terminarla"], "respuesta_correcta": "La tarea, luego jugar y después cenar", "retroalimentacion": "Organizar tu tiempo cumpliendo primero tus responsabilidades es un buen hábito."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Planificación", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "Si tienes un examen mañana, ¿qué debes hacer hoy?", "opciones": ["Ver tele todo el día", "Estudiar un rato y repasar", "Ir a dormir muy tarde", "Llorar"], "respuesta_correcta": "Estudiar un rato y repasar", "retroalimentacion": "Planificar tu tiempo de estudio te ayuda a estar preparado."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Memoria de Trabajo", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "Si te dicen: 'Trae tu cuaderno, tu lápiz y tu goma', ¿cuántas cosas debes recordar?", "opciones": ["1", "2", "3", "4"], "respuesta_correcta": "3", "retroalimentacion": "Debes recordar 3 objetos: cuaderno, lápiz y goma."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Flexibilidad", "oa": "OA 4", "dificultad": "Media", "pregunta": "Si vas a salir a jugar pelota, pero empieza a llover fuerte, ¿qué haces?", "opciones": ["Llorar porque se arruinó el día", "Salir igual y enfermarme", "Buscar un juego divertido para hacer dentro de casa", "Enojarme con el cielo"], "respuesta_correcta": "Buscar un juego divertido para hacer dentro de casa", "retroalimentacion": "Ser flexible significa adaptarse a los cambios cuando los planes fallan."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Control Inhibitorio", "oa": "OA 5", "dificultad": "Media", "pregunta": "Si estás en clases y tienes muchas ganas de contar un chiste, debes...", "opciones": ["Gritarlo de inmediato", "Esperar al recreo o pedir la palabra en el momento adecuado", "Interrumpir a la profesora", "Hacer ruidos raros"], "respuesta_correcta": "Esperar al recreo o pedir la palabra en el momento adecuado", "retroalimentacion": "Controlar nuestros impulsos ayuda a mantener el respeto en clases."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Planificación", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "Antes de empezar a hacer un dibujo muy bonito, es buena idea...", "opciones": ["Manchar la hoja", "Tener listos los lápices y pensar qué dibujar", "Romper el papel", "Botar los colores"], "respuesta_correcta": "Tener listos los lápices y pensar qué dibujar", "retroalimentacion": "Preparar los materiales y tener una idea es parte de planificar."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Organización", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué pasa si guardas tus juguetes todos desordenados?", "opciones": ["Será más fácil encontrarlos mañana", "Será muy difícil encontrar el que buscas la próxima vez", "Se multiplican", "La pieza se ve más linda"], "respuesta_correcta": "Será muy difícil encontrar el que buscas la próxima vez", "retroalimentacion": "La organización nos ayuda a saber dónde están nuestras cosas."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Control Inhibitorio", "oa": "OA 5", "dificultad": "Media", "pregunta": "Estás jugando un videojuego y tu mamá te llama a cenar, tú debes...", "opciones": ["Ignorarla", "Pausar el juego e ir a cenar", "Gritarle que espere una hora", "Llorar"], "respuesta_correcta": "Pausar el juego e ir a cenar", "retroalimentacion": "Saber detener una actividad divertida para cumplir con el horario es controlar nuestros impulsos."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Memoria de Trabajo", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "¿Para qué sirve anotar las tareas en una agenda?", "opciones": ["Para pintar los días", "Para descargar a nuestra mente de tener que recordar todo", "Para que el profesor nos rete", "Para hacer aviones de papel"], "respuesta_correcta": "Para descargar a nuestra mente de tener que recordar todo", "retroalimentacion": "La agenda nos ayuda a apoyar nuestra memoria y no olvidar obligaciones."},
    {"modulo_eduhome": "Taller de Funciones Ejecutivas", "eje": "Flexibilidad", "oa": "OA 4", "dificultad": "Media", "pregunta": "Si un problema matemático es muy difícil y no te sale usando una forma, ¿qué debes hacer?", "opciones": ["No hacerlo nunca más", "Borrar el cuaderno entero", "Intentar resolverlo buscando otra forma o estrategia distinta", "Llorar en la mesa"], "respuesta_correcta": "Intentar resolverlo buscando otra forma o estrategia distinta", "retroalimentacion": "La flexibilidad mental nos permite buscar caminos alternativos para lograr un objetivo."},

    # --- Taller de Movimiento y Coordinación (min 10) ---
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Motricidad", "oa": "OA 3", "dificultad": "Fácil", "pregunta": "¿Qué haces cuando saltas la cuerda?", "opciones": ["Duermes", "Mueves los pies y las manos coordinadamente", "Te quedas quieto", "Cantas bajito"], "respuesta_correcta": "Mueves los pies y las manos coordinadamente", "retroalimentacion": "Saltar requiere mover las manos y saltar al mismo tiempo."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Equilibrio", "oa": "OA 2", "dificultad": "Fácil", "pregunta": "¿Qué animal se caracteriza por pararse en una sola pata, mostrando buen equilibrio?", "opciones": ["El elefante", "El flamenco", "El gusano", "El león"], "respuesta_correcta": "El flamenco", "retroalimentacion": "El flamenco puede mantener su equilibrio en una sola pierna mucho tiempo."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Motricidad fina", "oa": "OA 4", "dificultad": "Media", "pregunta": "¿Cuál de estas actividades usa 'motricidad fina'?", "opciones": ["Correr rápido", "Saltar muy alto", "Enhebrar una aguja o escribir", "Patear un balón"], "respuesta_correcta": "Enhebrar una aguja o escribir", "retroalimentacion": "La motricidad fina usa los músculos pequeños de las manos con precisión."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Motricidad gruesa", "oa": "OA 5", "dificultad": "Fácil", "pregunta": "¿Qué deporte requiere correr y patear un balón?", "opciones": ["Ajedrez", "Fútbol", "Natación", "Ciclismo"], "respuesta_correcta": "Fútbol", "retroalimentacion": "El fútbol es un deporte de mucho movimiento de piernas."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Salud", "oa": "OA 1", "dificultad": "Media", "pregunta": "¿Por qué es importante hacer deporte y moverse?", "opciones": ["Para estar aburrido", "Para enfermarse", "Para mantener los músculos y el corazón sanos", "Para ver más televisión"], "respuesta_correcta": "Para mantener los músculos y el corazón sanos", "retroalimentacion": "El ejercicio fortalece todo nuestro cuerpo."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Equilibrio", "oa": "OA 2", "dificultad": "Media", "pregunta": "¿Qué pasa si intentas caminar por una línea recta en el suelo imaginando que es una cuerda floja?", "opciones": ["Estás practicando el equilibrio", "Estás saltando", "Estás corriendo", "Estás nadando"], "respuesta_correcta": "Estás practicando el equilibrio", "retroalimentacion": "Mantener el cuerpo centrado sobre una línea es un gran ejercicio de equilibrio."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Motricidad gruesa", "oa": "OA 5", "dificultad": "Fácil", "pregunta": "¿Qué parte de tu cuerpo usas más al saltar como un canguro?", "opciones": ["Las orejas", "Las piernas", "La nariz", "Las manos"], "respuesta_correcta": "Las piernas", "retroalimentacion": "Las piernas son fundamentales para darnos el impulso al saltar."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Motricidad fina", "oa": "OA 4", "dificultad": "Media", "pregunta": "Recortar una figura de papel con tijeras siguiendo la línea es un ejercicio de...", "opciones": ["Motricidad gruesa", "Motricidad fina", "Fuerza", "Respiración"], "respuesta_correcta": "Motricidad fina", "retroalimentacion": "Recortar con precisión usa los músculos de los dedos de forma coordinada."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Coordinación", "oa": "OA 3", "dificultad": "Difícil", "pregunta": "¿Qué deporte requiere que uses manos y pies de forma coordinada en el agua?", "opciones": ["El fútbol", "La natación", "El ajedrez", "Saltar la cuerda"], "respuesta_correcta": "La natación", "retroalimentacion": "En la natación debes patear y mover los brazos rítmicamente para avanzar."},
    {"modulo_eduhome": "Taller de Movimiento y Coordinación", "eje": "Salud", "oa": "OA 1", "dificultad": "Fácil", "pregunta": "Después de hacer mucho ejercicio y correr, ¿qué debes hacer?", "opciones": ["Comer muchos dulces", "No hacer nada", "Tomar agua para hidratarte", "Seguir corriendo hasta caer"], "respuesta_correcta": "Tomar agua para hidratarte", "retroalimentacion": "Al sudar perdemos agua, por lo que es vital beber agua para recuperarnos."}
]

def main():
    preguntas_finales = []
    contador_id = 1

    for p in preguntas_base:
        # Encontrar la asignatura basada en el modulo
        asignatura_encontrada = "Desconocida"
        for asig, mods in modulos_por_asignatura.items():
            if p["modulo_eduhome"] in mods:
                asignatura_encontrada = asig
                break

        pregunta_completa = {
            "id": contador_id,
            "asignatura": asignatura_encontrada,
            "modulo_eduhome": p["modulo_eduhome"],
            "eje": p["eje"],
            "oa": p["oa"],
            "dificultad": p["dificultad"],
            "pregunta": p["pregunta"],
            "opciones": p["opciones"],
            "respuesta_correcta": p["respuesta_correcta"],
            "retroalimentacion": p["retroalimentacion"]
        }
        preguntas_finales.append(pregunta_completa)
        contador_id += 1

    directorio = "data"
    if not os.path.exists(directorio):
        os.makedirs(directorio)

    ruta_archivo = os.path.join(directorio, "preguntas.json")
    with open(ruta_archivo, 'w', encoding='utf-8') as f:
        json.dump(preguntas_finales, f, ensure_ascii=False, indent=4)

    print(f"✅ Se han generado exitosamente {len(preguntas_finales)} preguntas de prueba.")
    print(f"📂 Archivo guardado en: {ruta_archivo}")

if __name__ == "__main__":
    main()
